version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: frontend # specify the directory of the Dockerfile
  ports:
    - "80:80"
  volumes:
    - ./frontend:/app # this will enable changes made to the angular app reflect in the container
 express: # name of the second service
  build: backend # specify the directory of the Dockerfile
  ports:
    - "3000:3000" #specify ports mapping
  dns:
    - 8.8.8.8
  network_mode: "bridge"