version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: frontend # specify the directory of the Dockerfile
  ports:
    - "80:80"
  volumes:
    - ./angular-client:/app # this will enable changes made to the angular app reflect in the container
 express: # name of the second service
  build: backend # specify the directory of the Dockerfile
  ports:
  - "3000:3000" #specify ports mapping
  links:
  - database # link this service to the database service
 database: # name of the third service
  image: mongo # specify image to build container from
  ports:
  - "27017:27017" # specify port forwarding  nginx: #name of the fourth service